/**
 * AgentLearningsStore — Self-Reported Capability Gaps
 *
 * Implements AI-AGENT-LEARNINGS-BRD Phase 1: the agent-written half of the
 * learnings loop. Quality incidents (user-flagged, evidence-only) are Phase 2
 * and deliberately do not exist here yet.
 *
 * WHY ONLY CAPABILITY GAPS
 * The agent is a reliable reporter of its own tool list and an unreliable
 * reporter of its own mistakes. "I was asked about trips and have no trip
 * tools" is verifiable; "here is why I stated a budget that does not exist" is
 * a plausible narrative generated by the same process that produced the wrong
 * answer. The `kind` field exists for Phase 2, but nothing the model can call
 * is able to set it to anything else (D-L01, enforced in the tool schema).
 *
 * SECURITY
 * - SEC-L001: learnings are advisory. Nothing here applies a change; a human
 *   reads them and decides. That review step is the control, so no code path
 *   may consume a learning automatically.
 * - SEC-L002: `title` and `detail` are model-authored and therefore untrusted.
 *   Anything rendering them must treat them as data and show provenance.
 * - SEC-L003/REQ-L031: stored in app storage only. Never GitHub, never the
 *   repo — evidence is adjacent to family financial conversation.
 * - SEC-L006: there is no read method exposed to the agent, and no tool wraps
 *   one. A learning shaped by injected content that could be read back later
 *   would be prompt injection with durable storage.
 * - SEC-L008: recording never throws. A dropped learning is a nuisance; a
 *   failed user turn is not an acceptable price for diagnostic bookkeeping.
 */

import { Mutex } from 'async-mutex';
import { createHash, randomUUID } from 'crypto';
import type { DataService } from './dataService';
import { childLogger } from '../utils/logger';
import { redactSecretsInText } from '../utils/redaction';

const log = childLogger('agentLearningsStore');

/**
 * Enumerated capability keys (REQ-L004).
 *
 * Free text cannot be clustered, counted, or trusted, and occurrence count is
 * the only demand signal a two-person app will ever produce. Keys are coarse on
 * purpose: the point is "which area is the agent blind in", not a taxonomy.
 */
export const CAPABILITY_KEYS = [
  'tasks.read',
  'tasks.write',
  'trips.read',
  'trips.write',
  'projects.read',
  'projects.write',
  'budgets.read',
  'budgets.write',
  'transactions.read',
  'transactions.write',
  'categories.write',
  'accounts.read',
  'reports.read',
  'wishlist.read',
  'other',
] as const;

export type CapabilityKey = (typeof CAPABILITY_KEYS)[number];

export function isCapabilityKey(value: unknown): value is CapabilityKey {
  return typeof value === 'string' && (CAPABILITY_KEYS as readonly string[]).includes(value);
}

export type LearningKind = 'capability_gap' | 'quality_incident';
export type LearningStatus = 'open' | 'accepted' | 'rejected' | 'shipped';

export interface AgentLearning {
  id: string;
  familyId: string;
  kind: LearningKind;
  status: LearningStatus;
  source: 'agent' | 'user_flag';
  capabilityKey: CapabilityKey | null;
  /** Model-authored — untrusted (SEC-L002). */
  title: string;
  /** Model-authored — untrusted (SEC-L002). */
  detail: string;
  /** User-authored, stored separately so provenance is never ambiguous. */
  userNote: string | null;
  fingerprint: string;
  occurrenceCount: number;
  firstSeenAt: string;
  lastSeenAt: string;
  conversationId: string;
  traceIds: string[];
  evidenceBundleId: string | null;
  reportedByUserId: string | null;
  resolution: string | null;
  resolvedAt: string | null;
}

/** SEC-L005 — Q-L01 defaults, revisit after real usage. */
export const MAX_PER_CONVERSATION = 2;
export const MAX_PER_DAY = 20;

/** REQ-L032 */
const RESOLVED_RETENTION_DAYS = 180;

/** Max traces linked to one learning — recurrence is counted, not accumulated. */
const MAX_LINKED_TRACES = 20;

const MAX_TITLE_LEN = 200;
const MAX_DETAIL_LEN = 4000;

export type RecordOutcome =
  | { recorded: true; learning: AgentLearning; deduped: boolean }
  | { recorded: false; reason: 'rate_limited' | 'suppressed' | 'error' };

export interface RecordLearningInput {
  familyId: string;
  conversationId: string;
  capabilityKey: CapabilityKey;
  title: string;
  detail: string;
  traceId: string;
}

/**
 * Fingerprint for deduplication (REQ-L020).
 *
 * Normalizes aggressively — lowercase, collapse whitespace, strip punctuation
 * and digits — because the model will phrase the same gap differently every
 * time. Over-merging distinct gaps is the better failure: an under-merged
 * collection is forty copies of one complaint and stops being read.
 */
export function fingerprintOf(kind: LearningKind, capabilityKey: string | null, title: string): string {
  const normalized = title
    .toLowerCase()
    .replace(/[0-9]+/g, '')
    .replace(/[^a-z\s]/g, '')
    .replace(/\s+/g, ' ')
    .trim();
  return createHash('sha256').update(`${kind}|${capabilityKey ?? ''}|${normalized}`).digest('hex').slice(0, 16);
}

export class AgentLearningsStore {
  private mutex = new Mutex();

  constructor(private readonly dataService: DataService) {}

  private key(familyId: string): string {
    return `agent_learnings_${familyId}`;
  }

  private async readAll(familyId: string): Promise<AgentLearning[]> {
    return (await this.dataService.getData<AgentLearning[]>(this.key(familyId))) ?? [];
  }

  /**
   * Record an agent-written capability gap.
   *
   * Returns an outcome rather than throwing so the caller can decide whether to
   * surface a notice. Never throws (SEC-L008).
   */
  async recordCapabilityGap(input: RecordLearningInput): Promise<RecordOutcome> {
    const release = await this.mutex.acquire();
    try {
      const all = await this.readAll(input.familyId);
      const now = new Date().toISOString();

      const fingerprint = fingerprintOf('capability_gap', input.capabilityKey, input.title);

      // REQ-L022: a rejected gap means "we are not doing this". It must not
      // resurface weekly. Checked before rate limits so a suppressed write
      // does not consume quota.
      if (all.some(l => l.fingerprint === fingerprint && l.status === 'rejected')) {
        return { recorded: false, reason: 'suppressed' };
      }

      // REQ-L021: fold into an existing open record rather than duplicating.
      // Deliberately only 'open' — an accepted item is already queued for work,
      // and a shipped one recurring is a regression that deserves a new record
      // (REQ-L023).
      const existing = all.find(l => l.fingerprint === fingerprint && l.status === 'open');
      if (existing) {
        existing.occurrenceCount += 1;
        existing.lastSeenAt = now;
        if (!existing.traceIds.includes(input.traceId) && existing.traceIds.length < MAX_LINKED_TRACES) {
          existing.traceIds.push(input.traceId);
        }
        await this.dataService.saveData(this.key(input.familyId), this.applyRetention(all));
        return { recorded: true, learning: existing, deduped: true };
      }

      // SEC-L005: caps apply to NEW records only. Deduping an existing gap is
      // free — otherwise a genuinely repeated gap would silently stop counting.
      if (!this.withinRateLimits(all, input.conversationId)) {
        log.warn(
          { familyId: input.familyId, conversationId: input.conversationId, capabilityKey: input.capabilityKey },
          'agent learning dropped — rate limited',
        );
        return { recorded: false, reason: 'rate_limited' };
      }

      const learning: AgentLearning = {
        id: `learning_${randomUUID()}`,
        familyId: input.familyId,
        kind: 'capability_gap',
        status: 'open',
        source: 'agent',
        capabilityKey: input.capabilityKey,
        // SEC-L004 (TD-029). Redact BEFORE truncating: slicing first can cut a
        // token in half and leave a fragment that no longer matches a pattern
        // but is still a fragment of a credential.
        title: redactSecretsInText(input.title).slice(0, MAX_TITLE_LEN),
        detail: redactSecretsInText(input.detail).slice(0, MAX_DETAIL_LEN),
        userNote: null,
        fingerprint,
        occurrenceCount: 1,
        firstSeenAt: now,
        lastSeenAt: now,
        conversationId: input.conversationId,
        traceIds: [input.traceId],
        evidenceBundleId: null,
        reportedByUserId: null,
        resolution: null,
        resolvedAt: null,
      };

      await this.dataService.saveData(this.key(input.familyId), this.applyRetention([...all, learning]));
      return { recorded: true, learning, deduped: false };
    } catch (error) {
      log.error({ err: error, familyId: input.familyId }, 'failed to record agent learning');
      return { recorded: false, reason: 'error' };
    } finally {
      release();
    }
  }

  private withinRateLimits(all: AgentLearning[], conversationId: string): boolean {
    const dayAgo = Date.now() - 24 * 60 * 60 * 1000;

    const inConversation = all.filter(
      l => l.source === 'agent' && l.conversationId === conversationId,
    ).length;
    if (inConversation >= MAX_PER_CONVERSATION) return false;

    const today = all.filter(
      l => l.source === 'agent' && Date.parse(l.firstSeenAt) >= dayAgo,
    ).length;
    return today < MAX_PER_DAY;
  }

  /** REQ-L032: open and accepted are kept indefinitely; resolved items age out. */
  private applyRetention(learnings: AgentLearning[], now = Date.now()): AgentLearning[] {
    const cutoff = now - RESOLVED_RETENTION_DAYS * 24 * 60 * 60 * 1000;
    return learnings.filter(l => {
      if (l.status === 'open' || l.status === 'accepted') return true;
      const resolved = l.resolvedAt ? Date.parse(l.resolvedAt) : Date.parse(l.lastSeenAt);
      return Number.isNaN(resolved) ? true : resolved >= cutoff;
    });
  }

  // ==========================================================================
  // Maintainer-facing reads. NOT reachable from any tool (SEC-L006).
  // ==========================================================================

  /** Open learnings, most-reported first — the ordering /evaluate-learnings wants. */
  async listOpen(familyId: string): Promise<AgentLearning[]> {
    const all = await this.readAll(familyId);
    return all
      .filter(l => l.status === 'open')
      .sort((a, b) => b.occurrenceCount - a.occurrenceCount || a.firstSeenAt.localeCompare(b.firstSeenAt));
  }

  async list(familyId: string): Promise<AgentLearning[]> {
    return this.readAll(familyId);
  }

  /**
   * Disposition a learning (REQ-L040, REQ-L041).
   *
   * A resolution note is mandatory: six months on, a rejected item with no
   * reason is indistinguishable from an unreviewed one.
   */
  async setStatus(
    familyId: string,
    id: string,
    status: Exclude<LearningStatus, 'open'>,
    resolution: string,
  ): Promise<AgentLearning | null> {
    if (!resolution.trim()) throw new Error('A resolution note is required to disposition a learning');

    const release = await this.mutex.acquire();
    try {
      const all = await this.readAll(familyId);
      const target = all.find(l => l.id === id);
      if (!target) return null;

      target.status = status;
      target.resolution = resolution.trim();
      target.resolvedAt = new Date().toISOString();
      await this.dataService.saveData(this.key(familyId), all);
      return target;
    } finally {
      release();
    }
  }
}
